### PR TITLE
Correct filter models

### PR DESCRIPTION
**Pull request by asevos**
I moved every filter to a separate file, created filter condition classes. All filters have correct format now. 
All filter properties with default values were wrapped in `Nullable<T>`.
I also wrote some test cases for filters. For this I changed  `RestClient.defaultSerializerSettings` access to `protected`, so I could use in tests serializer settings identical to settings in `RestClient`

### CODE REVIEW

**Review by KoditkarVedant — COMMENTED** [review]
@asevos Does it make sense to move Condition classes as part of respective Filter class and rename them to just `Condition`. Then we can use them as `[Filter].Condition`?

Rest all LGTM.

**Comment by asevos** [comment]
@KoditkarVedant thank you for reviewing!
Yeah, moving conditions to be nested in filter class is a good idea, should've done that from the start. I will update my PR with this changes later today.

**Comment by KoditkarVedant** [comment]
@asevos I've added editorconfig to the solution. you might wanna run the `dotnet format`.

**Comment by asevos** [comment]
@KoditkarVedant I moved conditions, formatted my files, added constructors to filters (as discussed in my [constructor proposal ](https://github.com/notion-dotnet/notion-sdk-net/issues/21)) and added to readme a section on how to query a db

**Review by KoditkarVedant — APPROVED** [review]
LGTM. Appreciate adding instructions on readme file.

**Pull request merged**
