### PR TITLE
upgrade Microsoft.SourceLink.GitHub version

### LINKED ISSUE #332: Update to latest version of Microsoft.SourceLink.GitHub
Update to latest version of Microsoft.SourceLink.GitHub

### PR DESCRIPTION
**Pull request by vinibeloni**
## Description

Upgrade Microsoft.SourceLink.GitHub package version to 1.1.1

Fixes #332

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I just run `dotnet build` because this package has no code impact.

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by KoditkarVedant — APPROVED** [review]
LGTM

**Comment by KoditkarVedant** [comment]
@vinibeloni Someone already asked to work on it - let me see if they still want to else, I'll accept your change.

**Comment by vinibeloni** [comment]
> @vinibeloni Someone already asked to work on it - let me see if they still want to else, I'll accept your change.

thanks! I will wait, of course.

**Comment by vinibeloni** [comment]
@KoditkarVedant can you merge please?

**Pull request merged**
