### PR TITLE
#390: Add missing property in paginated response

### LINKED ISSUE #390: Add missing type property in Paginated response.
Paginated Response is missing a type property.

https://developers.notion.com/reference/intro#responses

### PR DESCRIPTION
**Pull request by kashifsoofi**
## Description

Add missing property in paginated response.

Fixes #390 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by KoditkarVedant** [comment]
You might wanna remove the type property from Retrieve Comments Response.
image

**Review by ksvaibhav — COMMENTED** [review]
left a comment

**Comment by kashifsoofi** [comment]
> It would have been easier to ask first if you could work on the issue to avoid duplicate work...

Apologies

**Comment by kashifsoofi** [comment]
> You might wanna remove the type property from Retrieve Comments Response. image

Done

**Pull request merged**
