### PR TITLE
Added Color abstraction (#251)

### LINKED ISSUE #251: Block `colors` are now supported in the API
Notion has added support for block colors in the Notion Public API. There is now a `color` keyword for the following block types: `paragraph`, `heading_1`, `heading_2`, `heading_3`, `bulleted_list_item`, `numbered_list_item`, `to_do`, `toggle`, `callout`, `quote`, and `table_of_contents`. 

For these block types, the block color is returned in the [block object](https://developers.notion.com/reference/block), and you can use the [update block](https://developers.notion.com/reference/update-a-block), [append block children](https://developers.notion.com/reference/append-block-children), and [create page](https://developers.notion.com/reference/post-page) endpoints to update the color of existing blocks and create new blocks with color.

The colors supported are `default`, `gray`, `brown`, `orange`, `yellow`, `green`, `blue`, `purple`, `pink`, `red`, `gray_background`, `brown_background`, `orange_background`, `yellow_background`, `green_background`, `blue_background`, `purple_background`, `pink_background`, and `red_background`.

**Example block object**
```json
{
    "object": "block",
    "id": "79bc0ae2-b002-4ecd-92db-870354734aaf",
    "created_time": "2022-03-03T22:49:00.000Z",
    "last_edited_time": "2022-03-03T22:49:00.000Z",
    "created_by": {
        "object": "user",
        "id": "914ff1b3-45c7-48dc-b2c2-be37d21e7695"
    },
    "last_edited_by": {
        "object": "user",
        "id": "914ff1b3-45c7-48dc-b2c2-be37d21e7695"
    },
    "has_children": false,
    "archived": false,
    "type": "callout",
    "callout": {
        "rich_text": [
            {
                "type": "text",
                "text": {
                    "content": "This block has color!",
                    "link": null
                },
                "annotations": {
                    "bold": false,
                    "italic": false,
                    "strikethrough": false,
                    "underline": false,
                    "code": false,
                    "color": "default"
                },
                "plain_text": "This block has color!",
                "href": null
            }
        ],
        "icon": {
            "type": "emoji",
            "emoji": "💡"
        },
        "color": "green_background"
    }
}
```

**Notion changelog:** https://developers.notion.com/changelog/block-colors-are-now-supported-in-the-api

### PR DESCRIPTION
**Pull request by HermanSchoenfeld**
- Fixed #251 
- Color is now an enum in the DTO's
- Added missing Color property to all (relevant) blocks

### CODE REVIEW

**Review by KoditkarVedant — APPROVED** [review]
LGTM.

**Comment by KoditkarVedant** [comment]
@HermanSchoenfeld There are few checks are failing both are related to code analysis and styling. Try running `dotnet format` it should resolve most of them.

Can you added the link to the issue you are fixing with this? I believe it is #251, right?

**Comment by HermanSchoenfeld** [comment]
Hi Vedant, can we speak in private? My email is ***@***.***

**Comment by HermanSchoenfeld** [comment]
All formatting issues are resolved. I believe the LGTM issue is related to .NET 6 targetting. I've not changed any targets so this is not due to my changes.

**Pull request merged**
